language: python
python:
  - 3.6
  - 3.7
  - 3.8
# no virtualenv
#virtualenv:
#  system_site_packages: false

# Setup anaconda
before_install:
  # we need blas.h
  - sudo apt-get update
  #- sudo apt-get install -qq libblas-dev
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda create --quiet --yes -n buildenv python=$TRAVIS_PYTHON_VERSION
  - source activate buildenv
  - conda install --yes numpy scipy matplotlib nose setuptools coverage
  - pip install python-coveralls
  - python setup.py install

# Run the tests
script: nosetests --with-coverage --cover-package=filterdesigner filterdesigner

# Calculate coverage
after_success:
  - coveralls
